Repository team-pofo/pofo-spring, pull requests merged in 2024-12, with the labels that each got.

#47 refactor: 공통 응답 처리 및 인증/인가 에러 처리
  pofo-api/src/main/kotlin/org/pofo/api/common/exception/handler/ApiExceptionHandler.kt
  pofo-api/src/main/kotlin/org/pofo/api/common/exception/handler/GlobalGraphQLExceptionHandler.kt
  pofo-api/src/main/kotlin/org/pofo/api/common/response/ApiResponse.kt
  pofo-api/src/main/kotlin/org/pofo/api/controller/AutocompleteController.kt
  pofo-api/src/main/kotlin/org/pofo/api/controller/UserController.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/SecurityConfig.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/exception/handler/CommonAccessDeniedHandler.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/exception/handler/CommonAuthenticationEntryPoint.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/exception/handler/CommonAuthenticationFailureHandler.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/exception/handler/CommonAuthenticationSuccessHandler.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/ProjectService.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/UserService.kt
  pofo-common/src/main/kotlin/org/pofo/common/error/CustomError.kt
  pofo-common/src/main/kotlin/org/pofo/common/error/ErrorType.kt
  pofo-common/src/main/kotlin/org/pofo/common/exception/CustomException.kt
  pofo-common/src/main/kotlin/org/pofo/common/exception/ErrorCode.kt
  pofo-domain/build.gradle.kts
Labels: feature, refactor

#49 fix: dev, prod 환경 분리
  .gitignore
  docker/docker-compose.database.yml
  pofo-api/src/main/kotlin/org/pofo/api/controller/AutocompleteController.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/SecurityConfig.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/UserService.kt
  pofo-api/src/main/resources/application-oauth2.yml
  pofo-api/src/main/resources/application.yml
  pofo-domain/src/main/resources/application-db.yml
  pofo-infra/src/main/java/org/pofo/infra/elasticsearch/config/OpenSearchConfig.java
  pofo-infra/src/main/resources/application-elastic.yml
  pofo-infra/src/main/resources/elastic/tech-mapping.json
  pofo-infra/src/main/resources/elastic/tech-setting.json
Labels: fix, infra

#57 feat: domain property 추가 및 cors 설정
  pofo-api/Dockerfile
  pofo-api/src/main/kotlin/org/pofo/api/security/SecurityConfig.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/oauth2/OAuth2AuthenticationFailureHandler.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/oauth2/OAuth2AuthenticationSuccessHandler.kt
  pofo-api/src/main/resources/application-oauth2.yml
  pofo-api/src/main/resources/application.yml
Labels: feature

#60 fix: RefreshToken 쿠키의 만료 기간 수정
  pofo-api/src/main/kotlin/org/pofo/api/controller/UserController.kt
Labels: fix

#61 feat: 4xx 상황의 에러 핸들링 추가
  pofo-api/src/main/kotlin/org/pofo/api/common/exception/handler/ApiExceptionHandler.kt
  pofo-common/src/main/kotlin/org/pofo/common/exception/ErrorCode.kt
Labels: feature

#65 hotfix: re-issue uri permitAll
  .github/workflows/CI.yml
  pofo-api/src/main/kotlin/org/pofo/api/security/SecurityConfig.kt
Labels: fix

#64 feat: Swagger API Docs 추가
  pofo-api/build.gradle.kts
  pofo-api/src/main/kotlin/org/pofo/api/common/response/ApiResponse.kt
  pofo-api/src/main/kotlin/org/pofo/api/config/SwaggerConfig.kt
  pofo-api/src/main/kotlin/org/pofo/api/controller/AutocompleteController.kt
  pofo-api/src/main/kotlin/org/pofo/api/controller/ImageController.kt
  pofo-api/src/main/kotlin/org/pofo/api/controller/UserController.kt
  pofo-api/src/main/kotlin/org/pofo/api/docs/AutocompleteApiDocs.kt
  pofo-api/src/main/kotlin/org/pofo/api/docs/ImageApiDocs.kt
  pofo-api/src/main/kotlin/org/pofo/api/docs/UserApiDocs.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/SecurityConfig.kt
  pofo-api/src/main/resources/application.yml
  pofo-api/src/test/kotlin/org/pofo/api/controller/UserControllerTest.kt
  pofo-common/src/main/kotlin/org/pofo/common/response/Version.kt
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/user/User.java
Labels: feature

#69 feat: 프로젝트 스택 추가
  .gitignore
  data_crawling/stack_to_enum.py
  pofo-api/src/main/kotlin/org/pofo/api/controller/ProjectController.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/CreateProjectRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/UpdateProjectRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/ProjectService.kt
  pofo-api/src/main/resources/graphql/project.graphqls
  pofo-api/src/main/resources/graphql/project.stack.graphqls
  pofo-api/src/main/resources/graphql/user.graphqls
  pofo-api/src/test/kotlin/org/pofo/api/controller/ProjectControllerTest.kt
  pofo-api/src/test/kotlin/org/pofo/api/fixture/ProjectFixture.kt
  pofo-common/src/main/kotlin/org/pofo/common/exception/ErrorCode.kt
  pofo-domain/build.gradle.kts
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/Project.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectStack.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectStackListConverter.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectCustomRepository.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectCustomRepositoryImpl.java
Labels: feature

#72 feat: 프로젝트 검색 기능 추가
  pofo-api/src/main/kotlin/org/pofo/api/controller/ProjectController.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/CreateProjectRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectCreateRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectListResponse.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectResponse.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectSearchRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectUpdateRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/UpdateProjectRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/ProjectService.kt
  pofo-api/src/main/resources/graphql/project.graphqls
  pofo-api/src/main/resources/graphql/project.stack.graphqls
  pofo-api/src/test/kotlin/org/pofo/api/controller/ProjectControllerTest.kt
  pofo-api/src/test/kotlin/org/pofo/api/fixture/ProjectFixture.kt
  pofo-api/src/test/resources/graphql-test/createProject.graphql
  pofo-api/src/test/resources/graphql-test/getAllProjectsByPagination.graphql
  pofo-api/src/test/resources/graphql-test/getProjectById.graphql
  pofo-api/src/test/resources/graphql-test/updateProject.graphql
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/Project.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectCategory.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectList.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectStack.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectStackListConverter.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/Stack.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectCustomRepository.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectCustomRepositoryImpl.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectRepository.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/StackRepository.java
Labels: feature

#75 feat: 프로젝트 카테고리 다중화
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectCreateRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectResponse.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectSearchRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/dto/ProjectUpdateRequest.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/ProjectService.kt
  pofo-api/src/main/resources/graphql/project.graphqls
  pofo-api/src/test/kotlin/org/pofo/api/controller/ProjectControllerTest.kt
  pofo-api/src/test/kotlin/org/pofo/api/fixture/ProjectFixture.kt
  pofo-api/src/test/resources/graphql-test/getProjectById.graphql
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/Category.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/Project.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/ProjectCategory.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectCustomRepository.java
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/project/repository/ProjectCustomRepositoryImpl.java
Labels: feature

#77 feat: 깃허브 프로필 사진 적용
  pofo-api/src/main/kotlin/org/pofo/api/security/oauth2/OAuth2AuthenticationService.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/oauth2/userProperties/GithubOAuth2UserProperties.kt
  pofo-api/src/main/kotlin/org/pofo/api/security/oauth2/userProperties/OAuth2UserProperties.kt
  pofo-api/src/main/kotlin/org/pofo/api/service/UserService.kt
  pofo-domain/src/main/java/org/pofo/domain/rds/domain/user/User.java
Labels: feature
